services:
  quvels_auth:
    container_name: quvels_auth
    image: quvels_auth:0.0.1
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - quvels_network
    depends_on:
      - postgres
  postgres:
    container_name: quvels_auth_db
    image: postgres:13.3-alpine
    networks:
      - quvels_network
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - quvels_auth_db:/var/lib/postgresql/data
networks:
  quvels_network:
volumes:
  quvels_auth_db: